name: PSPNet
n_gpu: 1
use_synch_bn: False
arch:
  type: PSPNet
  args:
    backbone: resnet50
    freeze_bn: False
    freeze_backbone: False

train_loader:
  type: CityScapes
  args:
    data_dir: C:\Documents\Datasets\CityScapes
    batch_size: 8
    base_size: 400
    crop_size: 380
    augment: True
    shuffle: True
    scale: True
    flip: True
    rotate: True
    blur: False
    split: train
    num_workers: 8

val_loader:
  type: CityScapes
  args:
    data_dir: C:\Documents\Datasets\CityScapes
    batch_size: 8
    crop_size: 480
    val: True
    split: val
    num_workers: 4

optimizer:
  type: SGD
  differential_lr: True
  args:
    lr: 0.01
    weight_decay: 1e-4
    momentum: 0.9

loss: CrossEntropyLoss2d
ignore_index: 255
lr_scheduler:
  type: Poly
  args: {}

trainer:
  epochs: 80
  save_dir: saved/
  save_period: 10
  monitor: max Mean_IoU
  early_stop: 10
  tensorboard: True
  log_dir: saved/runs
  log_per_iter: 20
  val: True
  val_per_epochs: 5

resume:
device:
